from enum import Enum

class UserStatus(Enum):
    SELECT_NONE = None
    SELECT_DEVICE = 0
    SELECT_MODEM_MEDIUM = 1
    SELECT_MODEM_BRAND = 2
    SELECT_MODEM_MODEL = 3
    SELECT_PLAN = 100
    SELECT_PRECAUTION = 200
    SELECT_PRECAUTION_INFO = 201
    
    